/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SudokuDetector */

#ifndef _Included_SudokuDetector
#define _Included_SudokuDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SudokuDetector
 * Method:    setSourceImage
 * Signature: ([III)Z
 */
JNIEXPORT jboolean JNICALL Java_SudokuDetector_setSourceImage
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     SudokuDetector
 * Method:    detectSudoku
 * Signature: ([[I)Z
 */
JNIEXPORT jboolean JNICALL Java_SudokuDetector_detectSudoku
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
